import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import ConfettiProvider from "@/components/providers/confetti-provider";
import ReactQueryProvider from "@/provider/react-query-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			appearance={{
				variables: { colorPrimary: 'black' },
			}}
		>
			<html lang="en">
				<ReactQueryProvider>
					<body className={inter.className}>
						{children}
					</body>
				</ReactQueryProvider>
				<ConfettiProvider />
				<Toaster />
			</html>
		</ClerkProvider>
	);
}
